// Merged upstream entries; named subset: jsdoc/flat/recommended
import { fileURLToPath } from 'node:url';

const config = {
  rules: {
    'react/display-name': 'off',
    'react/jsx-key': 'error',
    'react/jsx-no-duplicate-props': 'error',
    'react/jsx-no-target-blank': 'error',
    'react/jsx-no-undef': 'error',
    'react/no-children-prop': 'off',
    'react/no-danger-with-children': 'error',
    'react/no-direct-mutation-state': 'error',
    'react/no-find-dom-node': 'error',
    'react/no-is-mounted': 'error',
    'react/no-string-refs': 'error',
    'react/no-unescaped-entities': 'error',
    'wordpress/jsx-no-comment-textnodes': 'error',
    'wordpress/no-render-return-value': 'error',
    'react/exhaustive-deps': 'warn',
    'react/rules-of-hooks': 'error',
    'wordpress/no-unused-vars-before-return': [
      'error',
      {
        excludePattern: '^use',
      },
    ],
    'jsdoc/check-tag-names': 'error',
    'jsdoc/check-values': 'off',
    'jsdoc/empty-tags': 'error',
    'jsdoc/no-types': 'off',
    'jsdoc/require-description': 'off',
    'jsdoc/require-param-description': 'off',
    'jsdoc/require-param-name': 'error',
    'jsdoc/require-property-description': 'error',
    'jsdoc/require-property-name': 'error',
    'jsdoc/require-returns-description': 'error',
    camelcase: 'error',
    curly: 'error',
    'dot-notation': 'error',
    eqeqeq: 'error',
    'no-alert': 'error',
    'no-bitwise': 'error',
    'no-caller': 'error',
    'no-cond-assign': 'error',
    'no-console': 'error',
    'no-debugger': 'error',
    'no-dupe-args': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-else-return': 'error',
    'no-eval': 'error',
    'no-fallthrough': 'error',
    'no-irregular-whitespace': 'error',
    'no-lonely-if': 'error',
    'no-mixed-operators': 'off',
    'no-multi-str': 'error',
    'no-nested-ternary': 'error',
    'no-redeclare': 'error',
    'no-undef-init': 'error',
    'no-unreachable': 'error',
    'no-unsafe-negation': 'error',
    'no-unused-expressions': 'error',
    'no-useless-return': 'error',
    'no-with': 'error',
    'valid-typeof': 'error',
    'vars-on-top': 'off',
    'no-dupe-class-members': 'error',
    'no-duplicate-imports': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-constructor': 'error',
    'no-var': 'error',
    'object-shorthand': 'error',
    'prefer-const': [
      'error',
      {
        destructuring: 'all',
      },
    ],
    'wordpress/i18n-ellipsis': 'error',
    'wordpress/i18n-hyphenated-range': 'error',
    'wordpress/i18n-no-collapsible-whitespace': 'error',
    'wordpress/i18n-no-flanking-whitespace': 'error',
    'wordpress/i18n-no-placeholders-only': 'error',
    'wordpress/i18n-no-variables': 'error',
    'wordpress/i18n-text-domain': 'error',
    'wordpress/i18n-translator-comments': 'error',
    'wordpress/valid-sprintf': 'error',
    'unicorn/empty-brace-spaces': 'off',
    'unicorn/no-nested-ternary': 'off',
    'unicorn/number-literal-case': 'off',
    'unicorn/template-indent': 'off',
  },
};

export default {
  ...config,
  extends: fileURLToPath(new URL('./01.mjs', import.meta.url)),
};
